### ISSUE TITLE
Code Zone disappears 

### ISSUE THREAD

**Issue by martinmestres** [cutelabnyc/nested-tuplets#2]
Coding zone disappears after doing something else like editing MIDI clip

WIN 10 - LIVE 11

**Comment by starakaj** [comment]
Thanks for reporting this. This is a known issue, unfortunately the code view doesn't draw right on Live 11. Fixing it will probably require changes to Live and/or Max, so I don't have an ETA for you, but we're working on it.

**Comment by starakaj** [comment]
Curious to know if the latest version of Nestup (you should have gotten an email about this) fixes the issue for you, as it specifically addressed exactly this issue.

**Comment by martinmestres** [comment]
Hi, yes, now it works as expected ☺

Have a good day

[image: Sans titre-1.png]

Martin Mestres


[image: Final).png] <https://www.facebook.com/martinmestresmusic/>
<https://www.youtube.com/channel/UCsfQbWaOmWiDUN4FwbcFFJg> [image:
instagram-new-flat-128x128.png]



Le mar. 20 avr. 2021 à 22:56, Sam Tarakajian ***@***.***> a
écrit :

**Comment by starakaj** [comment]
Magnifique :)
