### ISSUE TITLE
Code box is whited out and doesn't allow fo

### ISSUE THREAD

**Issue by dasanb135** [cutelabnyc/nested-tuplets#3]
The code box is whited out and won't load presets or let me write Nestup expressions. Tried reinstalling and restarting. Surely I'm doing something wrong here. 
Live 10.1.1
<img width="474" alt="Screen Shot 2021-04-07 at 1 32 54 PM" src="https://user-images.githubusercontent.com/82113502/113909566-d098b980-97a5-11eb-81fb-a006ed012cb1.png">

**Comment by starakaj** [comment]
Does this persist after you restart your computer?

The problem has to do with how Live is resolving paths to Max resources. Did you try to unfreeze the device by any chance (click the edit button)? Also are you on Windows or Mac?

**Comment by dasanb135** [comment]
Yes it continues after I restarted. I've just tried to hit the edit button a couple of times and Max crashes instead of opening up the patch. This doesn't happen with any of my other m4L devices as of right now. I am on Mac. Thanks for the response. 
<img width="1000" alt="Screen Shot 2021-04-07 at 3 46 37 PM" src="https://user-images.githubusercontent.com/82113502/113924968-76edba80-97b8-11eb-9955-00e65444eecb.png">

**Comment by dasanb135** [comment]
Also just got this message. Seems strange because my Max is running 64 bit. 
{
	"version" : "Version 8.1.2 (0c813b3) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.14.3 (Build 18D109) x86_64",
	"samplerate" : 48000,
	"iovs" : 512,
	"sigvs" : 64,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "subscription",
	"machine_id" : "5550502eee991ef5ead83ea6095327eb",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "on",
	"pollthrottle" : 40,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 33.333332061767578,
	"schedslop" : 25.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"glengine" : "gl2",
	"packages" : 	{
		"BEAP" : "1.0.2",
		"hap" : "1.0.6",
		"jit.mo" : "1.1.2",
		"LowkeyNW" : "1.2.0",
		"max-mxj" : "7.2.5",
		"MC Movement Studies" : "1.0.0",
		"Mira" : "1.2.1",
		"Node For Max" : "1.3.2",
		"VIDDLL" : "1.2.1",
		"Video and Graphics" : "7.2.0",
		"Virtual Sound Macros" : "",
		"Vizzie" : "2.0.3"
	}



<img width="1042" alt="Screen Shot 2021-04-07 at 3 55 39 PM" src="https://user-images.githubusercontent.com/82113502/113926299-fd56cc00-97b9-11eb-820e-9569ee186dde.png">

**Comment by starakaj** [comment]
Funny, the crash report says Max 8.0.4, and the message from Max says Max 8.1.2. Is Live configured to use the bundled version of Max? Or are you using a locally installed version? It might be that the bundled version of Max, version 8.0.4, needs to be updated.

**Comment by callnasty** [comment]
I'm try to run nestup in Ableton Live 10 (on Windows 7, with Max 8.0.0), but I get this old-school looking error message:
![nestuperr](https://user-images.githubusercontent.com/73963950/114871628-c2781800-9df9-11eb-9a0a-6f4ae80ee0dd.jpg)
Saying something like "Navigation to the web page was canceled." I'm quite new to Max and can't really resolve the issue.

**Comment by callnasty** [comment]
Thank you very much! I will give it a try. Congratulations for the great work, by the way!

**Comment by starakaj** [comment]
Closing as I assume this got fixed, please feel free to reopen if appropriate.
