### ISSUE TITLE
Missing Phrase class

### ISSUE THREAD

**Issue by aricl** [cutelabnyc/nested-tuplets#4]
When attempting to run `yarn start -i input/easy.rhy` after building the project I got the following error:

```
.../nested-tuplets/cli.js:17
	const phrases = parseTree.map(p => new Phrase(p));
	                                   ^

TypeError: Phrase is not a constructor
```

I'm pretty sure this is due to the use of the `Phrase` class in `cli.js`, which doesn't exist in the `index.js` file. Since `Phrase` is not really being used in `cli.js` it can just be deleted.

I'm happy to create the PR for this.

**Comment by starakaj** [comment]
I would love a PR!

**Comment by aricl** [comment]
Great, just figured out how to do that! https://github.com/cutelabnyc/nested-tuplets/pull/5
