### ISSUE TITLE
No Live/ Max for Live user

### ISSUE THREAD

**Issue by hanspukke** [cutelabnyc/nested-tuplets#8]
Hi,

I'am loving Nestup!! Really great!
But I don't use Live nor Max for Live (but Max).

I make attempts to use the Nestup-Website offline, but it still depends on an Internet connection to get the sounds and it returns to the default values every time the site is reloaded which makes it practically unusable for developing something seriously. If at least the midi-file would be saved (updated) automatically..
Do you, by chance, have any plans to make Nestup accessable to the rest of us, who don't use Live?
I'am willing to collect and spend some money for such a proposition..
Thank you for an answer!

best

ole

oleschmidt.info

**Comment by jinpavg** [comment]
Dear ole, thank you for letting us know about your interest. We do hope to work on a VST for Nestup, but we do not have a timeline for this yet.

In the meantime, have you checked out the "Share" function on the nestup.cutelab.nyc website? This will generate a link which will hold the state of the Nestup webpage at the time you click "Share." This will help with the issue you are having with the site returning to default values. 

Thank you, again, for writing us!

Alex

**Comment by hanspukke** [comment]
Thank you for the response!

 

Nestup- and the idea behind it- is really a gamechanger. The field of pitches is explored widely, Nestup has the potential to explore and extend the rhythmic domain!

Please keep me posted about your plans!

 

Thanks!

 

ole

 
 

Gesendet: Dienstag, 22. Juni 2021 um 22:59 Uhr
Von: "Alex Van Gils" ***@***.***>
An: "cutelabnyc/nested-tuplets" ***@***.***>
Cc: "hanspukke" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [cutelabnyc/nested-tuplets] No Live/ Max for Live user (#8)


 

Dear ole, thank you for letting us know about your interest. We do hope to work on a VST for Nestup, but we do not have a timeline for this yet.

In the meantime, have you checked out the "Share" function on the nestup.cutelab.nyc website? This will generate a link which will hold the state of the Nestup webpage at the time you click "Share." This will help with the issue you are having with the site returning to default values.

Thank you, again, for writing us!

Alex
